const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const {build}=require('./build'),{validate}=require('./validate'),{Collector,currentComparison}=require('./collector');
const {eventFacts,matchEvent,analyticsFor,comparison,ROUTES}=require('./matching');
const {parseOdds,FlashscoreOdds,ProviderError,http}=require('./providers');
const {write,read,key}=require('./storage');
const fixture=require('./fixtures/flashscore.json');
const row={snapshot_at:'2026-09-22T17:26:11.788Z',match_id:'test-match',event_id:'poly-event',market_id:'poly-market',condition_id:'condition',outcome_id:'over',token_id:'token-over',sport:'soccer',league_name:'Categoría Primera B',league_code:'col2',match_title:'CD Real Santander vs. Orsomarso SC',game_start_time:'2026-09-22T21:00:00.000Z',family:'totals',market_type:'totals',period:'match',line:1.5,outcome_line:1.5,outcome:'Over',probability_percent:70,price:0.7,decimal_odds:1.429,custom_preserved:{nested:['untouched']}};
const facts=eventFacts(row),quotes=parseOdds(fixture.response,fixture.event,'2026-09-22T20:00:00.000Z');
function temp(t){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'betx-layer-'));t.after(()=>fs.rmSync(dir,{recursive:true,force:true}));return dir;}
async function layer(t,rows=[row],options={}){const dir=temp(t);fs.writeFileSync(path.join(dir,'combo-markets.jsonl'),rows.map(JSON.stringify).join('\n')+'\n');const root=path.join(dir,'combo-2');await build(dir,root,{discovery:async()=>({candidates:[fixture.event],errors:{},diagnostics:[]}),odds:{fetchEvent:async()=>({quotes,observed_at:'2026-09-22T20:00:00.000Z'})},...options});return {dir,root};}
test('real Flashscore contract: event identity, known bookmakers and odds arithmetic',()=>{assert(quotes.length>0);assert(quotes.some(q=>q.bookmaker_name==='Betfair'));const c=comparison(row,quotes,facts);assert(c.betfair.matched);assert.equal(c.betfair.probability_percent,100/c.betfair.decimal_odds);assert.equal(c.comparison.probability_difference_pp,70-100/c.betfair.decimal_odds);assert.throws(()=>parseOdds(fixture.response,{...fixture.event,event_id:'wrong'},'now'));});
test('fail closed for line, family, period, player/team, selection and binary No',()=>{for(const patch of [{line:9.25,outcome_line:9.25},{family:'corners_totals'},{family:'team_totals'},{family:'player_props'},{period:'set_1'},{outcome:'No'},{sport:'baseball'},{outcome:'Mystery'}])assert.equal(comparison({...row,...patch},quotes,facts).betfair.matched,false,JSON.stringify(patch));});
test('never use another bookmaker as Betfair; reject duplicate ambiguous quotes',()=>{const noBf=quotes.filter(q=>q.bookmaker_name!=='Betfair');assert.equal(comparison(row,noBf,facts).betfair.matched,false);const c=comparison(row,[...quotes,...quotes],facts);assert.equal(c.betfair.matched,false);});
test('strict ordered event matching rejects wrong competition/time/scope and ambiguity',()=>{assert.equal(matchEvent(facts,[fixture.event],'flashscore').match_status,'matched');for(const patch of [{participants:[...fixture.event.participants].reverse()},{competition:'Different competition'},{scope:'game'},{start_time:'2026-09-23T21:00:00Z'},{sport:'tennis'}])assert.equal(matchEvent(facts,[{...fixture.event,...patch}],'flashscore').event_url,null);assert.equal(matchEvent(facts,[fixture.event,{...fixture.event,event_id:'second'}],'flashscore').match_status,'ambiguous');});
test('esports routes and strict series/game/BO boundaries',()=>{assert.deepEqual(ROUTES.dota2,['dotabuff','opendota','liquipedia']);assert.deepEqual(ROUTES.cs2,['hltv','liquipedia']);const f={sport:'esports',discipline:'cs2',participants:['A','B'],competition:'Cup',start_time:'2026-09-22T21:00:00Z',scope:'series',best_of:3};const c={...f,provider:'hltv',event_id:'123',event_url:'https://www.hltv.org/matches/123/a-vs-b'};assert.equal(analyticsFor(f,[c]).provider,'hltv');assert.equal(analyticsFor(f,[c]).match_status,'matched');assert.equal(analyticsFor(f,[{...c,scope:'game'}]).event_url,null);assert.equal(analyticsFor(f,[{...c,best_of:1}]).event_url,null);assert.equal(analyticsFor({...f,discipline:'other'},[]).match_status,'provider_not_available');});
test('all rows unchanged, parent grouping, no missing sibling fill, bounded pages',async t=>{const rows=Array.from({length:20},(_,i)=>({...row,outcome_id:'o'+i,token_id:'t'+i}));let requests=0;const {dir,root}=await layer(t,rows,{odds:{fetchEvent:async()=>{requests++;return {quotes,observed_at:'2026-09-22T20:00:00Z'};}}});assert.equal(requests,1);assert.equal(validate(dir,root).outcomes,20);const e=read(path.join(root,'events',key(row.match_id),'index.json'));assert.equal(e.market_count,1);assert.equal(e.markets[0].parts.length,3);assert.equal(e.outcome_count,20);});
test('mixed or duplicate source snapshots fail; external errors retain all rows',async t=>{const {dir,root}=await layer(t,[row],{odds:{fetchEvent:async()=>{throw new Error('HTTP 429');}}});assert.equal(validate(dir,root).outcomes,1);assert.equal(read(path.join(root,'index.json')).build_status,'partial');fs.writeFileSync(path.join(dir,'combo-markets.jsonl'),JSON.stringify(row)+'\n'+JSON.stringify({...row,outcome_id:'second',snapshot_at:'different'})+'\n');await assert.rejects(build(dir,root,{offline:true}),/Mixed/);});
test('validator rejects changed Poly fields and mixed page IDs',async t=>{const {dir,root}=await layer(t);const e=read(path.join(root,'events',key(row.match_id),'index.json'));const file=path.join(root,e.markets[0].parts[0].path),part=read(file);part.market.outcomes[0].polymarket.price=0.1;write(file,part);assert.throws(()=>validate(dir,root));part.market.outcomes[0].polymarket.price=row.price;part.snapshot_id='other';write(file,part);assert.throws(()=>validate(dir,root));});
test('collector: 20 outcomes one request per cycle, 2s target, dedup, stop',async t=>{const {root}=await layer(t,Array.from({length:20},(_,i)=>({...row,outcome_id:'o'+i})));const registryPath=path.join(root,'registry/index.json'),registry=read(registryPath);registry.events.push(registry.events[0]);write(registryPath,registry);let clock=0,calls=0;const c=new Collector(root,{now:()=>clock,client:{fetchEvent:async()=>{calls++;return {quotes,observed_at:new Date(clock).toISOString()};}}});assert.equal(c.interval,2000);await c.tick();assert.equal(calls,1);clock=1999;await c.tick();assert.equal(calls,1);clock=2000;await c.tick();assert.equal(calls,2);assert.equal(fs.readFileSync(path.join(root,'runtime/history',key(fixture.event.event_id)+'.jsonl'),'utf8').trim().split('\n').length,1);c.stop();clock=4000;await c.tick();assert.equal(calls,2);});
test('collector backoff honors Retry-After, keeps last good quote, recovers',async t=>{const {root}=await layer(t);let clock=0,calls=0;const c=new Collector(root,{now:()=>clock,client:{fetchEvent:async()=>{calls++;if(calls===2)throw new ProviderError('rate limited',{status:429,retryAfterMs:10000});return {quotes,observed_at:new Date(clock).toISOString()};}}});await c.tick();clock=2000;await c.tick();const file=path.join(root,'runtime/current',key(fixture.event.event_id),'index.json');assert.equal(read(file).status,'stale');assert.equal(read(file).external_odds_observed_at,new Date(0).toISOString());clock=11999;await c.tick();assert.equal(calls,2);clock=12000;await c.tick();assert.equal(calls,3);assert.equal(read(file).status,'available');assert.equal(c.health.rate_limits,1);});
test('collector concurrency is bounded; overlapping ticks cannot duplicate requests',async t=>{const {root}=await layer(t);const registryPath=path.join(root,'registry/index.json'),reg=read(registryPath);for(let i=0;i<4;i++){const file=`registry/test-${i}.json`;write(path.join(root,file),{snapshot_id:reg.snapshot_id,snapshot_at:reg.snapshot_at,event:{...fixture.event,event_id:'test'+i}});reg.events.push(file);}write(registryPath,reg);let active=0,max=0,calls=0;const c=new Collector(root,{concurrency:2,client:{fetchEvent:async()=>{active++;calls++;max=Math.max(max,active);await new Promise(r=>setTimeout(r,5));active--;return {quotes:[],observed_at:new Date().toISOString()};}}});await Promise.all([c.tick(),c.tick()]);assert.equal(calls,5);assert.equal(max,2);});
test('HTTP adapter uses observed event query once and honors throttling',async()=>{let calls=0;const client=new FlashscoreOdds(async url=>{calls++;const u=new URL(url);assert.equal(u.searchParams.get('_hash'),'oce');assert.equal(u.searchParams.get('eventId'),fixture.event.event_id);return {ok:true,status:200,json:async()=>fixture.response};});await client.fetchEvent(fixture.event);assert.equal(calls,1);await assert.rejects(http('https://www.flashscore.com/',async()=>({ok:false,status:429,headers:{get:k=>k==='Retry-After'?'15':null},text:async()=>'Too many requests'})),e=>e.retryAfterMs===15000);});
test('collector cannot import scanner/discovery or commit; stopped on snapshot replacement',async t=>{const code=fs.readFileSync(__filename.replace('combo2.test.js','collector.js'),'utf8');assert(!/require\(['"](?:\.\.\/scanner|child_process|node:child_process)/.test(code));const {root}=await layer(t);const c=new Collector(root,{client:{fetchEvent:async()=>{throw new Error('must not run');}}});const index=read(path.join(root,'index.json'));index.snapshot_id='new';write(path.join(root,'index.json'),index);await assert.rejects(c.tick(),/Snapshot changed/);assert(c.stopped);});
test('429 pauses the provider globally, and restart does not duplicate history',async t=>{const {root}=await layer(t);let clock=0;const client={fetchEvent:async()=>({quotes,observed_at:new Date(clock).toISOString()})};const first=new Collector(root,{now:()=>clock,client});await first.tick();first.stop();clock=2000;const second=new Collector(root,{now:()=>clock,client});await second.tick();const history=path.join(root,'runtime/history',key(fixture.event.event_id)+'.jsonl');assert.equal(fs.readFileSync(history,'utf8').trim().split('\n').length,1);
 const regPath=path.join(root,'registry/index.json'),reg=read(regPath);write(path.join(root,'registry/another.json'),{snapshot_id:reg.snapshot_id,snapshot_at:reg.snapshot_at,event:{...fixture.event,event_id:'another'}});reg.events.push('registry/another.json');write(regPath,reg);let calls=0;const throttled=new Collector(root,{concurrency:1,now:()=>clock,client:{fetchEvent:async()=>{calls++;throw new ProviderError('throttle',{status:429,retryAfterMs:60000});}}});await throttled.tick();assert.equal(calls,1);clock+=59999;await throttled.tick();assert.equal(calls,1);});
test('old reader navigation preserves page bytes and refreshes only manifest entries',async t=>{const {dir,root}=await layer(t);const text='Existing reader\n';fs.writeFileSync(path.join(dir,'CHAT-START.md'),text);fs.writeFileSync(path.join(dir,'README.md'),text);fs.writeFileSync(path.join(dir,'chat-manifest.json'),JSON.stringify({files:[{path:'CHAT-START.md'},{path:'README.md'}]}));require('./link-reader').link(dir);const once=fs.readFileSync(path.join(dir,'CHAT-START.md'),'utf8');require('./link-reader').link(dir);assert.equal(fs.readFileSync(path.join(dir,'CHAT-START.md'),'utf8'),once);const m=read(path.join(dir,'chat-manifest.json'));assert.equal(m.files[0].bytes,Buffer.byteLength(once));assert.equal(m.files[0].sha256,require('./storage').hash(once));assert.equal(validate(dir,root).outcomes,1);});
test('empty source and running-collector replacement guard',async t=>{const {dir,root}=await layer(t,[]);assert.equal(validate(dir,root).outcomes,0);fs.writeFileSync(path.join(root,'.collector.lock'),'test');await assert.rejects(build(dir,root,{offline:true}),/Stop the collector/);assert.equal(validate(dir,root).outcomes,0);});
test('validator rejects falsified analytics coverage and small-file overflow',async t=>{const {dir,root}=await layer(t);const file=path.join(root,'index.json'),index=read(file);index.coverage.normal.matched++;write(file,index);assert.throws(()=>validate(dir,root));assert.throws(()=>write(path.join(root,'too-large.json'),{text:'x'.repeat(60000)}),/exceeds/);});
