const test=require('node:test'),assert=require('node:assert/strict');
const {attachMarkets,fair}=require('./fair-probability');
const {parseOdds}=require('./providers');
const fixture=require('./fixtures/flashscore.json');
const base={event_id:'event',bookmaker_id:1,bookmaker_name:'Book',market_participant_ids:['home','away'],external_odds_observed_at:'2026-10-01T00:00:00Z',active:true,event_participant_id:null};
function pair(type='OVER_UNDER',odds=[1.8,2.0]){return attachMarkets(odds.map((decimal_odds,i)=>({...base,decimal_odds,event_participant_id:type==='ASIAN_HANDICAP'?['home','away'][i]:null,canonical:{sport:'soccer',discipline:null,type,period:'FULL_TIME',metric:'GOALS',line:type==='ASIAN_HANDICAP'?[1.5,-1.5][i]:1.5,selection:(type==='ASIAN_HANDICAP'?['HOME','AWAY']:['OVER','UNDER'])[i]}})));}
test('complete two-way fair probabilities sum to 100 and preserve selected raw odds',()=>{const q=pair(),a=q.map(fair);assert(Math.abs(a[0].fair_probability_percent-52.63157894736842)<1e-12);assert(Math.abs(a.reduce((n,x)=>n+x.fair_probability_percent,0)-100)<1e-12);assert.equal(q[0].decimal_odds,1.8);assert.equal(a[0].fair_probability_method,'proportional_complete_market');});
test('real full three-way market includes draw even when source shortlist has only one leg',()=>{const q=parseOdds(fixture.response,fixture.event,fixture.provenance.observed_at).filter(q=>q.canonical?.type==='HOME_DRAW_AWAY'&&q.bookmaker_id===15);assert.equal(q.length,3);assert(q.every(q=>fair(q).fair_probability_status==='available'));assert(Math.abs(q.reduce((n,q)=>n+fair(q).fair_probability_percent,0)-100)<1e-12);assert.equal(fair(q[0]).fair_probability_percent,fair(JSON.parse(JSON.stringify(q[0]))).fair_probability_percent);});
test('inactive missing duplicate wrong-line wrong-book and mismatched evidence cannot produce fair probability',()=>{const q=pair()[0];for(const mutate of [x=>x.full_market.outcomes.pop(),x=>x.full_market.outcomes.push(x.full_market.outcomes[0]),x=>x.full_market.outcomes[1].active=false,x=>x.full_market.outcomes[1].decimal_odds=1,x=>x.full_market.outcomes[1].line=2.5,x=>x.full_market.bookmaker_id=2,x=>x.full_market.event_id='other',x=>x.full_market.period='FIRST_HALF',x=>x.full_market.observed_at='later',x=>x.decimal_odds=1.7,x=>delete x.full_market]){const x=structuredClone(q);mutate(x);assert.equal(fair(x).fair_probability_percent,null);}});
test('opposing handicap lines are paired by home sign and participant ID',()=>{const q=pair('ASIAN_HANDICAP');assert(q.every(q=>fair(q).fair_probability_status==='available'));let x=structuredClone(q[0]);x.full_market.outcomes[1].line=1.5;assert.equal(fair(x).fair_probability_percent,null);x=structuredClone(q[0]);x.full_market.outcomes[1].event_participant_id='home';assert.equal(fair(x).fair_probability_percent,null);});
test('line period metric book and observation boundaries cannot be combined',()=>{for(const mutate of [x=>x.bookmaker_id=2,x=>x.canonical.period='FIRST_HALF',x=>x.canonical.metric='CORNERS',x=>x.canonical.line=2.5,x=>x.external_odds_observed_at='later',x=>x.event_id='other']){const q=pair().map(x=>{const y=structuredClone(x);delete y.full_market;return y});mutate(q[1]);assert(attachMarkets(q).every(q=>fair(q).fair_probability_percent===null));}});
test('overlapping double chance and push/quarter-line markets do not get a synthetic fair probability',()=>{for(const type of ['DOUBLE_CHANCE','UNKNOWN']){const x=pair()[0];x.canonical.type=type;assert.equal(fair(x).fair_probability_percent,null);}for(const line of [1,1.25,1.75]){const x=pair()[0];x.canonical.line=line;assert.equal(fair(x).fair_probability_percent,null);}});
test('BTTS full binary market is exhaustive and saved fair values are always recomputed',()=>{const q=attachMarkets(['YES','NO'].map((selection,i)=>({...base,decimal_odds:[1.6,2.2][i],canonical:{sport:'soccer',discipline:null,type:'BOTH_TEAMS_TO_SCORE',period:'FIRST_HALF',selection}})));assert(Math.abs(q.reduce((n,q)=>n+fair(q).fair_probability_percent,0)-100)<1e-12);assert.notEqual(fair({...q[0],fair_probability_percent:99}).fair_probability_percent,99);});

