const {comparison}=require('./matching');
const {write,MAX_BYTES}=require('./storage');
const fs=require('node:fs');
const path=require('node:path');
const SCHEMA_VERSION=3;
const median=values=>{const v=values.slice().sort((a,b)=>a-b),n=v.length;return n?n%2?v[(n-1)/2]:(v[n/2-1]+v[n/2])/2:null;};
function summarize(row,bookmakers){
 const odds=bookmakers.map(q=>q.decimal_odds),implied=odds.map(x=>100/x),mid=median(implied),poly=Number.isFinite(row.probability_percent)?row.probability_percent:null;
 const edge=mid!==null&&poly!==null?mid-poly:null;
 return {bookmaker_count:odds.length,median_odds:median(odds),median_implied_probability_percent:mid,min_odds:odds.length?Math.min(...odds):null,max_odds:odds.length?Math.max(...odds):null,polymarket_vs_market_median_pp:edge===null?null:-edge,market_edge_pp:edge,method:'median_of_raw_implied_probabilities_no_margin_adjustment'};
}
function enrich(row,quotes,facts){const bookmakers=comparison(row,quotes,facts).bookmakers.filter(q=>q.bookmaker_id!==null&&q.bookmaker_id!==undefined&&typeof q.bookmaker_name==='string'&&q.bookmaker_name.trim()),bookmaker_aggregate=summarize(row,bookmakers);return {bookmakers,bookmaker_aggregate,market_edge_pp:bookmaker_aggregate.market_edge_pp};}
function rankingRow(event,outcome,outcomePath){return {outcome_id:outcome.outcome_id,match_id:event.match_id,market_id:outcome.polymarket.market_id,title:event.title,sport:event.sport,league_code:event.league_code,game_start_time:event.game_start_time,market_type:outcome.polymarket.market_type,family:outcome.polymarket.family,period:outcome.polymarket.period,line:outcome.polymarket.line,outcome:outcome.outcome,outcome_label:outcome.outcome_label||outcome.polymarket.question||outcome.outcome,polymarket_probability_percent:outcome.polymarket.probability_percent,...outcome.bookmaker_aggregate,event_path:`events/${require('./storage').key(event.match_id)}/index.json`,outcome_path:outcomePath};}
function rank(rows){return rows.filter(r=>Number.isFinite(r.market_edge_pp)).sort((a,b)=>b.market_edge_pp-a.market_edge_pp||(a.outcome_id<b.outcome_id?-1:a.outcome_id>b.outcome_id?1:0)).map((r,i)=>({rank:i+1,...r}));}
const esc=x=>String(x??'—').replace(/[\r\n]+/g,' ').replace(/[\\`*_{}[\]()<>#|]/g,'\\$&');
const num=(x,d=1)=>Number.isFinite(x)?x.toFixed(d):'—';
const signed=x=>Number.isFinite(x)?(x>0?'+':'')+num(x):'—';
function rankingPage(meta,items,page,pages){return `# Рейтинг исходов — страница ${page}\n\n[Combo 2.0](../../README.md) · [Все страницы рейтинга](index.md)\n\nСнимок: ${esc(meta.snapshot_at)}. ID: ${meta.snapshot_id}. Коэффициенты сохранены при сборе; это не live-цены.\n\n`+items.map(r=>`## ${r.rank}. ${esc(r.title)}\n\n**${esc(r.outcome_label)}** — ${esc(r.outcome)}\n\n${esc(r.sport)} · ${esc(r.league_code)} · ${esc(r.game_start_time)} · ${esc(r.family)} / ${esc(r.period)}\n\n| Показатель | Значение |\n|---|---:|\n| Polymarket | ${num(r.polymarket_probability_percent)}% |\n| БК | ${r.bookmaker_count} |\n| Median odds | ${num(r.median_odds,2)} |\n| Median implied | ${num(r.median_implied_probability_percent)}% |\n| Range | ${num(r.min_odds,2)}–${num(r.max_odds,2)} |\n| Polymarket vs market median | ${signed(r.polymarket_vs_market_median_pp)} п.п. |\n| **market_edge_pp** | **${signed(r.market_edge_pp)} п.п.** |\n\n[Событие](../../${r.event_path}) · [Исход и все БК](../../${r.outcome_path})\n`).join('\n')+`\n${page>1?`[← Назад](page-${page-1}.md) · `:''}[Оглавление](index.md)${page<pages?` · [Далее →](page-${page+1}.md)`:''}\n`;}
function rankingMenu(meta,items,pages,total){return `# Combo 2.0 — рейтинг исходов\n\n[Главная Combo 2.0](../../README.md) · [JSON-индекс](index.json)\n\nСнимок: ${esc(meta.snapshot_at)}. ID: ${meta.snapshot_id}.\n\nВ рейтинге: **${items.length}** исходов. Без подтверждённых коэффициентов или вероятности: **${total-items.length}**. Киберспорт исключён из Combo 2.0.\n\nСортировка: **market_edge_pp по убыванию**. Формула: медиана вероятностей БК − вероятность Polymarket. Положительное значение означает, что медианная вероятность БК выше. Показатель «Polymarket vs market median» имеет обратный знак.\n\nОдна БК — один подтверждённый коэффициент; Betfair учитывается наравне с остальными. Median implied = медиана значений 100 / кэф каждой БК, без удаления маржи. При чётном числе БК она может отличаться от 100 / Median odds. Минимум для рейтинга — одна БК; количество показано у каждого исхода. Это сравнение сохранённых цен, а не оценка доходности ставки.\n\n## Страницы\n\n${pages.length?pages.map((p,i)=>`- [${p.first_rank}–${p.last_rank}: страница ${i+1}](page-${i+1}.md)`).join('\n'):'Нет исходов с подтверждёнными коэффициентами.'}\n`;}
function home(meta,total,excluded,ranked){return `# BET-X — Combo 2.0\n\nСнимок: ${esc(meta.snapshot_at)}. ID: ${meta.snapshot_id}.\n\n- [**Рейтинг исходов по market_edge_pp**](rankings/market-edge/index.md) — ${ranked} исходов, по убыванию разницы «медианная вероятность БК − Polymarket».\n- [События и семейства рынков](index.json) — ${total} исходов.\n\nДля каждого исхода сохранены все подтверждённые БК, число БК, медианы коэффициентов и implied probability, диапазон и разница с Polymarket. Betfair — одна из БК без отдельного приоритета.\n\nКиберспорт исключён из Combo 2.0: ${excluded} исходов исходного снимка. Коэффициенты собираются один раз после нового сканирования, с паузой 2 секунды между запросами.\n`;}
function textFile(root,file,text){if(Buffer.byteLength(text)>MAX_BYTES)throw Error('Reader page too large: '+file);fs.mkdirSync(path.dirname(path.join(root,file)),{recursive:true});fs.writeFileSync(path.join(root,file),text);}
function writeRanking(root,meta,rows,total,excluded=0){const items=rank(rows),pages=[];for(let i=0;i<items.length;i+=20){const file=`rankings/market-edge/page-${i/20+1}.json`,part=items.slice(i,i+20);write(path.join(root,file),{...meta,items:part});textFile(root,file.replace('.json','.md'),rankingPage(meta,part,i/20+1,Math.ceil(items.length/20)));pages.push({path:file,outcomes:part.length,first_rank:i+1,last_rank:i+part.length});}const file='rankings/market-edge/index.json';write(path.join(root,file),{...meta,name:'Outcomes ranked by market_edge_pp',sort:'market_edge_pp descending, outcome_id ascending',definition:'median(100 / bookmaker decimal odds) - Polymarket probability percent',ranked_outcomes:items.length,unranked_outcomes:total-items.length,minimum_bookmakers:1,pages});textFile(root,'rankings/market-edge/index.md',rankingMenu(meta,items,pages,total));textFile(root,'README.md',home(meta,total,excluded,items.length));return {path:file,reader_path:'rankings/market-edge/index.md',ranked_outcomes:items.length,unranked_outcomes:total-items.length};}
module.exports={SCHEMA_VERSION,median,summarize,enrich,rankingRow,rank,writeRanking,rankingPage,rankingMenu,home};
