const {isEsports}=require('./matching');
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const {source,read,MAX_BYTES}=require('./storage');
const {comparison,directUrl}=require('./matching');
const {SCHEMA_VERSION,enrich,rankingRow,rank,rankingPage,rankingMenu,home}=require('./market-summary');
function validate(sourceDir,root){
 const src=source(sourceDir),index=read(path.join(root,'index.json'));assert.equal(index.source_sha256,src.sha256);assert.equal(index.snapshot_id,src.snapshot_id);const seen=[],counts={events:0,markets:0,bf:0,books:0};
 const modern=index.schema_version===SCHEMA_VERSION,eligible=modern?src.rows.filter(r=>index.exclusion_policy_version===2?!isEsports(r):r.sport!=='esports'):src.rows,ranking=[];
 const coverage={normal:{matched:0,unmatched:0,ambiguous:0},esports:{},flashscore_events:{}};
 const load=p=>{const file=path.resolve(root,p);assert(file.startsWith(path.resolve(root)+path.sep),'Unsafe path');assert(fs.statSync(file).size<=MAX_BYTES);const d=read(file);assert.equal(d.snapshot_id,index.snapshot_id);assert.equal(d.snapshot_at,index.snapshot_at);return d;};
 function bucket(b){const doc=load(b.path);if(doc.disciplines){assert.equal(b.events,doc.disciplines.reduce((n,d)=>n+d.events,0));assert.equal(b.outcomes,doc.disciplines.reduce((n,d)=>n+d.outcomes,0));for(const d of doc.disciplines)bucket(d);return;}let outcomes=0,events=0;for(const page of doc.pages)for(const entry of load(page).events){const e=load(entry.path);events++;counts.events++;
 if(modern)assert.notEqual(e.sport,'esports');
 const analytics=e.analytics;if(analytics.match_status==='matched')assert(directUrl(analytics.provider,analytics.event_url));else assert.equal(analytics.event_url,null);
 const fc=coverage.flashscore_events[e.sport]??={total:0,matched:0,unmatched:0,ambiguous:0};fc.total++;fc[e.odds_source.match_status]++;
 if(e.odds_source.match_status==='matched'){assert(directUrl('flashscore',e.odds_source.event_url));assert(e.odds_source.event_id);assert.deepEqual([...e.odds_source.participant_order].sort(),[0,1]);}else assert.equal(e.odds_source.event_id,null);
 if(e.sport!=='esports')coverage.normal[analytics.match_status]=(coverage.normal[analytics.match_status]||0)+1;
 else{const provider=analytics.provider||'unavailable';coverage.esports[provider]??={matched:0,unmatched:0,ambiguous:0,fallback_matched:0};const stat=coverage.esports[provider];stat[analytics.match_status]=(stat[analytics.match_status]||0)+1;if(analytics.match_status==='matched'&&analytics.route_position>0)stat.fallback_matched++;}
 let eventRows=0;const markets=e.markets||e.market_pages.flatMap(p=>load(p).markets);assert.equal(markets.length,e.market_count);for(const m of markets){counts.markets++;let n=0;for(const part of m.parts){const p=load(part.path);assert.equal(p.match_id,e.match_id);assert.equal(p.market.market_id,m.market_id);assert.equal(p.market.outcomes.length,part.outcomes);for(const out of p.market.outcomes){assert.equal(out.polymarket.match_id,e.match_id);assert.equal(out.polymarket.market_id,m.market_id);assert(!Object.hasOwn(out,'analytics'));seen.push(out.polymarket);n++;
 if(modern){const expected=enrich(out.polymarket,out.bookmakers,e.facts);assert.deepEqual(out.bookmakers,expected.bookmakers);assert.deepEqual(out.bookmaker_aggregate,expected.bookmaker_aggregate);assert.equal(out.market_edge_pp,expected.market_edge_pp);assert(!Object.hasOwn(out,'betfair'));assert(!Object.hasOwn(out,'comparison'));ranking.push(rankingRow(e,out,part.path));if(out.bookmakers.length)counts.books++;continue;}
 const recomputed=comparison(out.polymarket,out.bookmakers,e.facts);// A saved snapshot may predate support for this type; preserve its historical absence reason.
 const legacyUnsupported=out.betfair.matched===false&&out.betfair.reason==='unsupported_or_unproven_market_semantics'&&recomputed.betfair.matched===false&&recomputed.betfair.reason==='betfair_selection_not_available';
 assert.deepEqual(out.betfair,legacyUnsupported?{...recomputed.betfair,reason:out.betfair.reason}:recomputed.betfair);assert.deepEqual(out.comparison,recomputed.comparison);
 if(out.betfair.matched){counts.bf++;assert.equal(out.betfair.probability_percent,100/out.betfair.decimal_odds);assert.equal(out.comparison.probability_difference_pp,out.polymarket.probability_percent-out.betfair.probability_percent);}else assert.equal(out.comparison.probability_difference_pp,null);if(out.bookmakers.length)counts.books++;}}assert.equal(n,m.outcome_count);eventRows+=n;}assert.equal(eventRows,e.outcome_count);assert.equal(eventRows,entry.outcomes);outcomes+=eventRows;}
 assert.equal(events,b.events);assert.equal(outcomes,b.outcomes);}
 for(const b of index.sports)bucket(b);
 const sort=a=>a.slice().sort((a,b)=>a.outcome_id.localeCompare(b.outcome_id));assert.deepEqual(sort(seen),sort(eligible));assert.equal(seen.length,index.layer_outcomes);assert.equal(src.rows.length,index.source_outcomes);assert.equal(counts.events,index.events);assert.equal(counts.markets,index.markets);assert.equal(counts.books,index.coverage.bookmaker_outcomes);assert.equal(index.coverage.bookmaker_unmatched,seen.length-counts.books);
 if(modern){assert.deepEqual(index.excluded_outcomes,{esports:src.rows.length-eligible.length});assert(!Object.hasOwn(index.coverage,'betfair_matched'));assert(!Object.hasOwn(index.coverage,'esports'));const menu=load(index.market_edge_ranking.path),actual=[];for(const p of menu.pages){const page=load(p.path);assert.equal(page.items.length,p.outcomes);assert.equal(page.items[0].rank,p.first_rank);assert.equal(page.items.at(-1).rank,p.last_rank);actual.push(...page.items);}assert.deepEqual(actual,rank(ranking));assert.equal(menu.ranked_outcomes,actual.length);assert.equal(menu.unranked_outcomes,seen.length-actual.length);assert.equal(index.market_edge_ranking.ranked_outcomes,actual.length);assert.equal(index.market_edge_ranking.unranked_outcomes,seen.length-actual.length);}
 else{assert.equal(seen.length,index.source_outcomes);assert.equal(counts.bf,index.coverage.betfair_matched);assert.equal(index.coverage.betfair_unmatched,seen.length-counts.bf);assert.deepEqual(index.coverage.esports,coverage.esports);}
 assert.deepEqual(index.coverage.normal,coverage.normal);
 assert.deepEqual(index.coverage.flashscore_events,coverage.flashscore_events);
 if(modern){const meta={snapshot_id:index.snapshot_id,snapshot_at:index.snapshot_at},menu=load(index.market_edge_ranking.path),items=rank(ranking);assert.equal(index.market_edge_ranking.reader_path,'rankings/market-edge/index.md');const checkText=(file,text)=>assert.equal(fs.readFileSync(path.join(root,file),'utf8'),text);for(let i=0;i<menu.pages.length;i++){const p=menu.pages[i];checkText(p.path.replace('.json','.md'),rankingPage(meta,load(p.path).items,i+1,menu.pages.length));}checkText('rankings/market-edge/index.md',rankingMenu(meta,items,menu.pages,seen.length));checkText('README.md',home(meta,seen.length,index.excluded_outcomes.esports,items.length));}
 for(const p of load('registry/index.json').events)load(p);for(const p of load(index.diagnostics).pages)load(p);
 function walk(dir){for(const e of fs.readdirSync(dir,{withFileTypes:true})){const file=path.join(dir,e.name);if(e.isDirectory())walk(file);else if(e.name.endsWith('.json'))load(path.relative(root,file));else if(e.name.endsWith('.md'))assert(fs.statSync(file).size<=MAX_BYTES);}}walk(root);
 if(modern)delete counts.bf;
 return {valid:true,...counts,outcomes:seen.length,snapshot_id:index.snapshot_id};
}
module.exports={validate};
if(require.main===module)console.log(JSON.stringify(validate(process.argv[2]||'out',process.argv[3]||path.join(process.argv[2]||'out','combo-2'))));
